import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Cocktail Viewer",
    description: "Generated by Taha Emir Gökçegöz",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} min-h-screen flex flex-col`}>
                <header className="bg-blue-500 text-white p-4">
                    <Navbar />
                </header>
                {children}
            </body>
        </html>
    );
}
